### ISSUE TITLE
UI availability?

### ISSUE THREAD

**Issue by gtamas** [linkedin/QueryAnalyzerAgent#3]
I guess the UI developed by LinkedIn for this is not open source right?

Is there any open source UI for this project? Even a basic one?

**Comment by appigatla** [comment]
Hi @gtamas 

Yes, the UI is not open source as it uses lot of internal libraries. I don't think there is open source UI for this. As a work around, you can query the database and get the results in HTML by passing --html to mysql cli. This can be used for reporting also.
